# Generated by Django 4.2.3 on 2023-07-21 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Income_transaction',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Order disabled'), (1, 'Default status'), (2, 'Order Active'), (3, 'Order completed')], default=1)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
